title: "GAIL: Guaranteed Automatic Integration Library "
description: "GAIL is a suite of algorithms for integration problems in one, many dimensions, and whose answers are guaranteed to be correct. "
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
