% Guaranteed Automatic Integration Library (GAIL)
% Version 2.3.2, 2021
%
% Files
%   GAILstart      - Initialize all the GAIL paths and system parameters.
%   GAIL_Install   - Install or reinstall GAIL. Add GAIL paths to MATLAB search path.
%   GAIL_Uninstall - Uninstall GAIL. Remove GAIL paths from MATLAB search path
%   LICENSE        - License of GAIL
%   README         - Installation of and introduction to GAIL.
%   ReleaseNotes   - What is new in this version?
%
% Folders
%   Algorithms     - GAIL algorithms
%   Documentation  - GAIL documentation
%   OutputFiles    - Output generated by GAIL routines
%   Papers         - Papers and slides related to GAIL
%   Tests          - Unit tests, stress tests, automated tests of GAIL algorithms
%   ThirdParty     - Open-source tools used but not produced by the GAIL team
%   Workouts       - Workouts of GAIL algorithms
