%% Digital Option in Matlab
% An option whose payout is fixed after the underlying stock exceeds 
% the predetermined threshold or strike price. It is the type of option 
% in which the payoff can take only two possible outcomes, either 
% some fixed monetary amount or nothing at all.
% 
% There are two different types of Digital Options called _Cash_ and
% _Asset_ and both exists for calls and puts.


%% BlackSchoels model for ExactPrice
% The following formulas are from the BlackScholes model and them give the
% Exact Value for an Digital Option:
%
% $$\Phi(x)=1/\sqrt{(2\pi)}\int_{-\infty}^{x}e^{-\frac{1}{2}z^2}dz $$
%
% and,
%
% $$ d_1=\frac{\ln(\frac{S}{K})+(r-q+\sigma^2/2)T}{\sigma\sqrt{T}} $$
% $$\quad d_2=d_1-\sigma\sqrt{T} $$
%
% Where:
%
% _S_ - initial stock price
%
% _K_ - strike price
%
% _T_ - time to maturity
%
% _q_ - dividend rate
%
% _r_ - risk-free interest rate
%
% $\sigma$ - volatility
%
% $\Phi$ - cumulative distribution function of the normal distribution
%
%% Exact Price Formulas for Digital Options
% * Cash-or-nothing call
% 
% $$C=e^{-rT}\Phi(d_2)$$
% 
% * Cash-or-nothing put
% 
% $$P=e^{-rT}\Phi(-d_2)$$
% 
% * Asset-or-nothing call
% 
% $$C=Se^{-qT}\Phi(d_1)$$
% 
% * Asset-or-nothing put
% 
% $$P=Se^{-qT}\Phi(-d_1)$$

%% Example of pricing digital option for cash
% _optPrice_ is a MATLAB(R) class that uses _optPayoff_ parameters.
%
% Creating the _inp_ structure

inp.payoffParam.optType = {'digital'};      %Defining the Option Type
inp.payoffParam.cashAssetType = {'cash'};   %Defining the Digital Option Type
inp.assetParam.initPrice = 9;               %Defining the Inicial Stock Price as $9.00
inp.payoffParam.strike = 12;                %Defining the Strike Price as $12.00
inp.timeDim.timeVector = (0.25:0.25:1);     %Defining the Time as four trimesters.
inp.assetParam.interest = 0.01;             %Defining Interest Rate as 1%
inp.assetParam.volatility = 0.5;            %Defining the Volatility as 50%
inp.priceParam.absTol = 0.01;               %Defining the Absolute Tolerance as 1%
%%
% _tianci_ is the _optPrice_ class

tianci = optPrice(inp)
%%
% _hartur_ is the price of the option, generated by IID Monte Carlo

hartur = genOptPrice(tianci)
%% 
% As it can be seen the _exactPrice_ for _tianci_ is the same value of
% the _IID_MC_ price for _hartur_ with two decimal numbers, showing that
% the formula used is correct. The same result appears for the next 
% example using asset type.

%% Example of pricing digital option for asset
% _optPrice_ is a MATLAB(R) class that uses _optPayoff_ parameters.
% Creating the _inp_ structure

inp.payoffParam.optType = {'digital'};      %Defining the Option Type
inp.payoffParam.cashAssetType = {'asset'};  %Defining the Digital Option Type
inp.assetParam.initPrice = 9;               %Defining the Inicial Stock Price as $9.00
inp.payoffParam.strike = 12;                %Defining the Strike Price as $12.00
inp.timeDim.timeVector = (0.25:0.25:1);     %Defining the Time as four trimesters.
inp.assetParam.interest = 0.01;             %Defining Interest Rate as 1%
inp.assetParam.volatility = 0.5;            %Defining the Volatility as 50%
inp.priceParam.absTol = 0.01;               %Defining the Absolute Tolerance as 1%
%%
% _tianci_ is the _optPrice_ class

tianci = optPrice(inp)
%%
% _hartur_ is the price of the option, generated by IID Monte Carlo

hartur = genOptPrice(tianci)