% WORKOUTFUNAPPXOUTPUT
%
% Files
%
% WorkoutFunAppxConvTest1-2015-Jan-24-14-19-37.eps --- figure 1 generated
% by funappx_convetest.m to compare funappx_g and funappxglobal_g
% WorkoutFunAppxConvTest1-2015-Jan-24-14-19-37.eps --- figure 2 generated
% by funappx_convetest.m to compare funappx_g and funappxglobal_g
% WorkoutFunAppxTest-2015-Jan-24-14-17-40.eps --- figure generated by
% workout_funappx_g.m to compare funappx_g and funappxglobal_g
% WorkoutFunAppxConvTest1-2015-Jan-24-14-17-41.mat --- dataset generated by
% workout_funappx_g.m
