% WORKOUTFUNAPPXOUTPUT
%
% Files
%
% WorkoutFunAppxConvTest1-2015-03-05-23-42-06.eps --- figure 1 generated
% by funappx_convetest.m to compare funappx_g and funappxglobal_g
% WorkoutFunAppxConvTest2-2015-03-05-23-42-07.eps --- figure 2 generated
% by funappx_convetest.m to compare funappx_g and funappxglobal_g
% WorkoutFunAppxTest-2015-03-05-23-04-55.eps --- figure generated by
% workout_funappx_g.m to compare funappx_g and funappxglobal_g
% WorkoutFunAppxTest-2015-03-05-23-04-56.mat --- dataset generated by
% workout_funappx_g.m
