% WORKOUTFUNAPPXOUTPUT
%
% Files
%
% testfun-2017-07-19-14-52-45.eps --- figure 1 generate by 
%          workout_funappx.m to compare funappx_g and funappxglobal_g
%
% Workoutfunappx_gConvTest-2017-07-19-15-47-32.eps --- figure generated
%          by funappx_convetest.m to compare funappx_g and funappxglobal_g
%
% Workoutfunappx_gTest-2017-07-19-14-52-48.eps --- figure 2 generated by
%          workout_funappx_g.m to compare funappx_g and funappxglobal_g
%
% Workoutfunappx_gTest-2017-07-19-14-52-49.mat --- dataset generated by
%          workout_funappx_g.m
