% LLUISANTONIJIMENEZTHESIS
%
% Files
%
%   baker_example - Generates Figure 2.3 to show the Baker's transform
%   digital_lattices_example - Generates Figure 2.1 and 2.2 exemplifying
%             Sobol' and rank-1 lattices points.
%   SobolErrEstWalshCoeffPict - Generates Figure 3.1.
%   RunTestKeister - Generates a mat file with the results for the
%             Keister example (eq 3.13) with either
%		-param.method = {'cubSobol'}; For Figure 3.2
%		-param.method = {'cubLattice'}; For Figure 3.3
%               -param.method = {'cubSobolCLT'}; For Figure 3.4
%               -param.method = {'cubLatticeCLT'}; For Figure 3.5
%             This is the pure absolue error tolerance case.
%   RunTestGeo - Generates a mat file with the results for the
%             Geometric mean Asian option example (eq 3.14) with either
%		-param.method = {'cubSobol'}; For Figure 3.6
%		-param.method = {'cubLattice'}; For Figure 3.7
%               -param.method = {'cubSobolCLT'}; For Figure 3.8
%               -param.method = {'cubLatticeCLT'}; For Figure 3.9
%             This is the pure absolue error tolerance case.
%   RunTestKeister_rel - Generates a mat file with the results for the
%             Keister example (eq 3.13) with either
%		-param.method = {'cubSobol'}; For Figure 4.1
%		-param.method = {'cubLattice'}; For Figure 4.2
%             This is the hybrid error tolerance case.
%   DisplayTestResults_BlacknColor - Generates Figures 3.2 to 3.9 using
%             the mat files generated by RunTestKeister.m and RunTestGeo.m.
%   DisplayTestResults_BlacknColor_rel - Generates Figures 4.1 and 4.2 using
%             the mat files generated by RunTestKeister_rel.m.
%   article_scheme_S_3D - Generates Figure 5.1.
%   Keistertrue_check   - KEISTERTRUE computes the true value of the Keister integral in dimension d
%   TestSettings        - Test the new cubMC routine
%   TestSettings_rel    - Test the new cubMC routine
%   cubLattice_CLT      - CUBLATTICE_G Quasi-Monte Carlo method using rank-1 Lattices cubature
%   cubSobol_CLT        - CUBLATTICE_G Quasi-Monte Carlo method using rank-1 Lattices cubature
%   geoAsianCall        - This function chooses and sets up a test function from the parameters
%   randomchoiceKeister - Choose Keister function
%   plotTestColor       - 
%   plotTestColor_rel   - 
%   randomchoiceGeo     - 
