% Guaranteed Automatic Integration Library
% Version 1.3.1 05-Sep-2014
%
% Files
%   GAILstart      - Initialize all the GAIL paths and system parameters.
%   GAIL_Install   - Install GAIL. Add GAIL paths to MATLAB search path.
%   GAIL_Reinstall - Reinstall GAIL. Remove existing GAIL paths and add new ones.
%   GAIL_Uninstall - Uninstall GAIL. Remove GAIL paths from MATLAB search path
%   LICENSE        - License of GAIL
%   README         - Installation of and introduction to GAIL.
% 
% Folders
%   Algorithms     - GAIL algorithms
%   Documentation  - GAIL documentation
%   OutputFiles    - Output generated by GAIL routines
%   Papers         - Papers and slides related to GAIL
%   ThirdParty     - Open-source tools used but not produced by the GAIL team
%   UnitTests      - Unit tests of GAIL algorithms
%   Utilities      - Tools for the GAIL package
%   Workouts       - Workouts of GAIL algorithms
