% GAIL_MATLAB
%
% Files
%   GAILstart      - Initialize all the GAIL global parameters
%   GAIL_Install   - Install GAIL
%   GAIL_Reinstall - Reinstall GAIL
%   GAIL_Uninstall - Uninstall GAIL
%   LICENSE        - License of GAIL
%   README	   - Installation introduction
% 
% Folders
%   Algorithms     - GAIL algorithms
%   Documentation  - GAIL documentation
%   OutputFiles    - Output generated by GAIL routines
%   Papers         - Papers and slides related to GAIL
%   ThirdParty     - Open-source tools used but not produced by the GAIL team
%   UnitTests      - Unit tests of GAIL algorithms
%   Utilities      - Tools for the GAIL package
%   Workouts       - Workouts of GAIL algorithms
